### ISSUE TITLE
unable to package when image is added to wwwroot

### ISSUE THREAD

**Issue by R-Lamberson** [oqtane/oqtane.theme.cerulean#1]
After adding an image to the wwwroot in the project.  I am getting this error when attempting package

![image](https://user-images.githubusercontent.com/48865653/83173414-9ae36880-a0de-11ea-8fc4-8aaa6a62a19f.png)

Unsure why it is treating it differently than the theme.css

**Comment by sbwalker** [comment]
are you following the patterns outlined here:

https://github.com/oqtane/oqtane.framework/issues/532

Is the image in the wwwroot/Themes/YourThemeName folder?

**Comment by R-Lamberson** [comment]
ok I didn't see the patterns outline but I have now moved the images and rename the folders in the wwwroot/subfolders appropriately however I am still running into the same error when I execute the pack 
![image](https://user-images.githubusercontent.com/48865653/83179575-d20a4780-a0e7-11ea-956e-9b5491213508.png)

**Comment by R-Lamberson** [comment]
@sbwalker ok figured it out - had a path set incorrectly.  Also can this be done using dotnet pack rather than nuget pack or is there a difference there?
