### ISSUE TITLE
upgrading to .Net 5 causes error in release build

### ISSUE THREAD

**Issue by markdav-is** [oqtane/oqtane.theme.cerulean#3]
if I update the propjet version to net5.0 and build in release mode we get linker errors/

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unhandled exception. Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.Extensions.Localization, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'	Oqtane.Theme.Cerulean	C:\Users\mark\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.1\targets\Blazor.MonoRuntime.targets	326

**Comment by sbwalker** [comment]
So you are trying to use the Cerulean theme on Oqtane 2.0? Did you try to run the .NET 3.1 version.... it should work fine as there were no breaking changes. But if you want to upgrade it to .NET 5 you would need to update the target, the dependencies, the nuspec file paths, etc... if you build in Release mode it will create a nupkg package and you will want to make sure it included the correct files. The nupkg should be copied to the Oqtane.Server/wwwroot/Themes folder and should be installed automatically when you run Oqtane. You should ensure the correct DLL ends up in the /bin folder - are you running Oqtane 2.0 in Visual Studio or as a release version in IIS?

**Comment by sbwalker** [comment]
That’s an odd error message as themes do not have a dependency on Localization?

**Comment by sbwalker** [comment]
https://devblogs.microsoft.com/dotnet/app-trimming-in-net-5/

This may require further testing. It appears that Microsoft changed the linker behavior for Blazor in .NET 5.

**Comment by markdav-is** [comment]
It really odd because the linking looks like web assembly targets. And we are server... More investigation for sure...

**Comment by PoisnFang** [comment]
@markdav-is Can you share a fork with the changes you made?

**Comment by sbwalker** [comment]
Theme has been upgraded to .NET 5 and works fine

**Comment by markdav-is** [comment]
awesome thanks!
