### ISSUE TITLE
Theme is not rendered properly

### ISSUE THREAD

**Issue by vzdesic** [oqtane/oqtane.theme.cerulean#4]
After following steps:
1. Download code of this theme as zip file
2. Open and build solution without changing anything
3. Install and apply theme to oqtane.framework default site
4. Restart oqtane.framework 
5. Login to the site
6. Home page is rendered as it is shown in the following picture
![theme](https://user-images.githubusercontent.com/9677726/165379733-764f4aaa-1f5f-44bf-b7fc-0883b6505272.png)

**Comment by sbwalker** [comment]
@vzdesic this theme has not been actively maintained for 2 years - I would suggest you look at https://github.com/oqtane/oqtane.theme.bootswatch

**Comment by vzdesic** [comment]
I understand. 
Thanks!
